### ISSUE TITLE
Fix newlines

### ISSUE THREAD

**Issue by faem** [masudur-rahman/cheatsheets#1]
Fix newlines on https://github.com/masudur-rahman/cheatsheets/blob/09f91ee73afcd4b3aa9e3d61d1e02f054cda425c/kubeadm.md

**Comment by masudur-rahman** [comment]
Your issue has been resolved...
You can review it [here](https://github.com/masudur-rahman/cheatsheets/blob/0b5f88eac8d717ac0ddde0bf36ac49d5f98c4043/kubeadm.md).

**Comment by faem** [comment]
> Your issue has been resolved...
> You can review it [here](https://github.com/masudur-rahman/cheatsheets/blob/0b5f88eac8d717ac0ddde0bf36ac49d5f98c4043/kubeadm.md).

Thank you!

**Comment by masudur-rahman** [comment]
> > Your issue has been resolved...
> > You can review it [here](https://github.com/masudur-rahman/cheatsheets/blob/0b5f88eac8d717ac0ddde0bf36ac49d5f98c4043/kubeadm.md).
> 
> Thank you!

You are welcome... :100:
